name: Java CI with Maven

on:
  push:
    branches: [ main, 'hacking/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest

    steps:
    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 22
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd server
        ./mvnw -B verify --file pom.xml
